[package]
name = "fast-ovl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
primal = "0.3.0"

[dev-dependencies]
itertools = "0.10.3"

